spring.application.name=mediaStreamer

# MinIo Configuration
minio.url=http://localhost:9000

# MinIo Configuration
minio.access-key=myminiouser
minio.secret-key=myminiopassword

# MinIo Bucket Configuration
minio.video.bucket=videos
minio.video.chunks.bucket=video-chunks
minio.video.transcoded.chunks.bucket=video-transcoded-chunks

# RabbitMQ Configurations
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=ruser
spring.rabbitmq.password=rpass
spring.rabbitmq.virtual-host=/

# Enable H2 Console for visual debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database configuration (In-Memory i.e. mem for dev, or file-backed i.e. file: so it persists restarts)
spring.datasource.url=jdbc:h2:file:./mediastreamerdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Hibernate automatically create the tables based on entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sets the max size for a single file. For example, 50MB.
spring.servlet.multipart.max-file-size=10GB
# Sets the max size for the entire request. For example, 50MB.
spring.servlet.multipart.max-request-size=10GB
