spring.application.name=mediaStreamer

# MinIo Configuration
minio.url=http://localhost:9000

# MinIo Configuration
minio.access-key=myminiouser
minio.secret-key=myminiopassword

# MinIo Bucket Configuration
minio.video.bucket=videos
minio.video.metadata.bucket=video-metadata
minio.video.chunks.bucket=video-chunks
minio.video.transcoded.chunks.bucket=video-transcoded-chunks

# RabbitMQ Configurations
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=ruser
spring.rabbitmq.password=rpass
spring.rabbitmq.virtual-host=/

# Sets the max size for a single file. For example, 50MB.
spring.servlet.multipart.max-file-size=10GB
# Sets the max size for the entire request. For example, 50MB.
spring.servlet.multipart.max-request-size=10GB
